language: node_js
node_js:
  - "stable"
  - "8"

branches:
  only:
  - master

install:
  - cd TodoFrontend
  - npm install

script:
  - npm test

cache:
  directories:
    - TodoFrontend/node_modules